### ISSUE TITLE
Should not have fixed paths in the scripts.

### ISSUE THREAD

**Issue by SimonGoring** [PalEON-Project/PalEON-FIA#10]
Using fixed paths (for example to `C:\.....`) prevents reproducibility.  All paths should be relative, and there should be an explanation as to why they point to that directory.
@jpeters7

**Comment by jpeters7** [comment]
@SimonGoring 
Would a better way be to setwd() in the console when I start working on a project rather putting it at the top of script file and running it from in that file?  And if I do that then I make the paths be something like:  "./stats/output/filename.csv"

**Comment by SimonGoring** [comment]
In RStudio the project should always start in the appropriate directory (the directory in which the project is located).  Otherwise, yes.

**Comment by jpeters7** [comment]
Oh. So if I open up the project then I don't have to setwd()?
Now that I write that, it makes sense...

**Comment by jpeters7** [comment]
Fixed the directory paths!
