### ISSUE TITLE
question about taxa grouped as other hardwood

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PalEON-FIA#4]
In the PLS composition stat modeling we individually modeled cherry, dogwood and black gum/sweet gum. 

These are being translated to other hardwood in the FIA_conversion-SGD_remove_dups.csv despite the fact that I think they are individual taxa in Paleon level 3s.

**Comment by SimonGoring** [comment]
In the code itself, the only file that is used is `Conversion_tables/FIA_conversion_v02-SGD.csv`, which does seem to have the right conversions.  The only place that `FIA_conversion-SGD_remove_dups.csv` is used is in `fia2PalEON_v1-SGD.R`.  The file is referenced in some other files in the header comments, but not `source`d as far as I can tell.

**Comment by paciorek** [comment]
ok, thanks. I'll use FIA_conversion_v02-SGD.csv.  Not sure why I thought I
should use the remove_dups one.

Should the authoritative version of this conversion table be on the Wiki or
in the repository? Also should it be named based on the paleon conversion
table naming scheme. I.e., with "level3" and whatnot?

**Comment by SimonGoring** [comment]
I think you're confusing the PLSS-PFT conversion file (which is at version 0.4 and has "level"s) and the FIA-PFT conversion file which is at 0.2.

**Comment by paciorek** [comment]
well, I'm definitely confused but not sure in what way.

At this page on the Wiki:
https://paleon.geography.wisc.edu/doku.php/data_and_products;taxatranslation
we say that level 3f is the FIA species names. So I thought that meant that
we would have a translation from level 3f to level 3a for the FIA stat
modeling. In fact there is a level 3f to level 3a translation file on that
page of the  Wiki based on Sydne's work.

So I think we want an updated version of that 3f->3a translation posted on
the Wiki with appropriate naming, no? And I guess it would basically be
Sean's FIA_conversion_v02-SGD.csv?

chris

**Comment by SimonGoring** [comment]
Okay, sorry, I see what you're saying.  Yes.  We can just change the columns.  I thought you wanted to go from PLS to FIA, not the PLS aggregated.

The issue I want to resolve is, in Level 3a we have three "gum" classes: "Black gum", "sweet gum" and "black gum/sweet gum".

In Sean's (3f) version it is currently all going to "other hardwood".  Do we want to classify the gums into the three classes and then aggregate everything to "black gum/sweet gum" afterwards, or do you just want all the gums assigned to "black gum/sweet gum"?

**Comment by jpeters7** [comment]
My vote would be to continue to classify the gums into the three classes and then aggregate everything to black gum/sweet gum afterwards.  With the PLS data we have the black/sweet gum category for the cases where the surveyors just wrote gum instead of specifying if it was black or sweet.

**Comment by paciorek** [comment]
Keeping as 3 in principle is fine with me, but I'm confused about our
terminology is.

In FIA_conversion_v02-SGD.csv, I guess the level 3f designation is either
the first or second column?

And then is the PalEON column supposed to represent level 3a or level 3s?

If it's level 3a, then I agree that we should have 3 different gum
categories in that column. In that case I will then use my level3s.csv (bad
name as what it is is a file tha converts level 3a to level 3s) translation
table to get level3s from level3a.

If it's level 3s, then there should only be black gum/sweet gum, as that is
how the lumping works in level 3s.

**Comment by SimonGoring** [comment]
Yes, so here's the mapping as I see it:

https://github.com/PalEON-Project/PalEON-FIA/blob/master/Conversion_tables/FIA_conversion_v02-SGD.csv#L1

| scientific | common | acronym | spcd | pft | PalEON | scientific_name |
| --- | --- | --- | --- | --- | --- | --- |
| Level 3f | undoc. | undoc. | undoc. | Level 4 | Level 3a | Level 3f with underscores |

I want to keep the column names as is (except the PalEON), in part because the table comes explicitly from a paper.  I can change the `PalEON` code if people are concerned, but since we've now got this great discussion, I think we can leave the code as is.

**Comment by paciorek** [comment]
Sounds good.

1) I'd prefer PalEON_3a as the field name instead of PalEON

1a) Is the pft column based on the paper or a PalEON thing. If Paleon, I'd
suggest the field name be PalEON_4 or PalEON_pft_4

2) I think we're agreed that there should 3 potential gum categories in the
"PalEON" column and that gum not be translated to other hardwood.
Simon, I assume you'll make this fix?

**Comment by SimonGoring** [comment]
Okay, I've made the change to `Level 3a` from PalEON (and will push shortly).  One thing I just noticed is that the correct common names are actually sweetgum and blackgum, with no space. I think that's something we can address later maybe.

The pft/Level 4 change will not be made since the Level 4 is from Dietze & Moorecroft, not the Paleon designations we've used elsewhere.
